class Event:
    """Base class for all events."""
    pass

class MarketEvent(Event):
    """Indicates a new daily data point."""
    def __init__(self):
        self.type = 'MARKET'

class SignalEvent(Event):
    """Generated by the strategy, signals a trade."""
    def __init__(self, ticker, date, signal_type):
        self.type = 'SIGNAL'
        self.ticker = ticker
        self.date = date
        self.signal_type = signal_type # 'LONG', 'EXIT' or 'SHORT'

class OrderEvent(Event):
    """Firm order to the broker/portfolio."""
    def __init__(self, ticker, date, order_type, quantity, direction):
        self.type = 'ORDER'
        self.ticker = ticker
        self.date = date
        self.order_type = order_type # 'MKT' or 'LMT'
        self.quantity = quantity
        self.direction = direction # 'BUY' or 'SELL'
        
    def print_order(self):
        print(f"Order: {self.direction} {self.quantity} {self.ticker} on {self.date}")

class FillEvent(Event):
    """Filled order."""
    def __init__(self, timeindex, ticker, exchange, quantity, direction, fill_cost, commission=0.0):
        self.type = 'FILL'
        self.timeindex = timeindex
        self.ticker = ticker
        self.exchange = exchange
        self.quantity = quantity
        self.direction = direction
        self.fill_cost = fill_cost
        self.commission = commission
